language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
script:
  - python setup.py test
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: bradleyb
  password:
    secure: "RZ33roxL9T150NZuMUlfwNgSLP139dIvtfS0iFHUkz6Bab6aIxBPqC3ZdtArN/HZ9ikEKmCXDub9SQOzgTZp9ZuWzAXMEmah01rAmKwiRP0MJMDEbkRA5Va1dyzzipJgExDGqvmYAWVNBh2vJ3sitPZB3sRqsm54vrC6gbcNLGWDxXVcfglrINuS2TzgGr4MMtnKg7f3X6oOi2YiVHicslc8tU6ygQMhZOr01qVcRmRUHpct2Fd5EvtCKRtHktgSrCH0SNdv78mIEYGfpRk9J6BnhGX8mWX0WVvRk83qkEXdfvLKF6MUMQWT8QbiexSHbkwBnm+2mzS5ahv+YG3+6z4ntoxr/5BIm8oCoA2EHCBCDfEMcJaqqEUosegsWZUV5IA9ykIULy6V+6ZZ3qiDHABiC4U5tE+KZ5O5Xv6eC2XQjXcGmJ2m48LvNiRYZrKyKrS5SMP303jZsqqDvQS4H1bMBYkxTGlOh4KhJUi8eg/yroLwH6zG0A3Ymhs9D+AhqLg8f/Vnhb7whf0JYT51EpzuGUcn5CyLgvL3rH7AKecR3MI1Q8LzHRScORs4UfiO1OvY/fr5DfcrYxxezQyzx2sTR92c+fsikecNAS2zzt8pBQHt1UQbSbKJVIvuLs9mYy6HHbui9Ydm5unuiPowMvL+kdZhAu4CMx2LgZfwehA="
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
    tags: true
